---
  extends: [
    "airbnb-base",
    "plugin:vue/recommended"
  ]
  env:
    browser: true
    es6: true
  plugins: [
    "vue"
  ]
  rules:
    import/extensions: 0
    import/no-unresolved: 0
    no-new: 0
    max-len: [2, 80, 2, { "ignoreUrls": true }]
    quotes: [2, "single"]
  parserOptions:
    parser: "babel-eslint"
    ecmaVersion: 6
