title: Teaser Loop
status: ready

context:
  teaser:
    image: 
      url: https://placedog.net/500/300
      alt: Placeholder
    heading: Teaser Heading
    subHeading: Teaser Subheading
    excerpt: >-
      Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. <a href="#">Ut enim ad minima</a> veniam, quis nostrud exercitation.
    url: '#'