title: Accordion
status: ready

context:
  heading: Accordion Item
  content: >-
    Donec sed odio dui. Aenean lacinia bibendum nulla sed consectetur. Cras justo odio, dapibus ac facilisis in, egestas eget quam. Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh, ut fermentum massa justo sit amet risus. Vivamus sagittis lacus vel augue laoreet rutrum faucibus dolor auctor. Sed posuere consectetur est at lobortis.
  open: false

variants:
  -
    name: Open
    context:
      heading: Accordion Item Two
      open: true
