title: Mobile Menu
status: ready

context:
  items:
    -
      title: Parent Item One
      slug: 1
      url: '#'
      id: 1
    -
      title: Parent Item Two
      slug: 2
      url: '#'
      id: 2
      get_children:
        -
          title: Child Item One
          slug: 3
          url: '#'
          id: 3
        -
          title: Child Item Two
          slug: 4
          url: '#'
          id: 4
